# Generated by Django 5.2.16 on 2026-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_id', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hour', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('is_weekend', models.BooleanField()),
                ('road_type', models.CharField(max_length=100)),
                ('lanes', models.IntegerField()),
                ('traffic_signal', models.BooleanField()),
                ('weather', models.CharField(max_length=50)),
                ('visibility', models.CharField(max_length=50)),
                ('temperature', models.IntegerField()),
                ('traffic_density', models.CharField(max_length=20)),
                ('cause', models.CharField(max_length=200)),
                ('accident_severity', models.CharField(max_length=20)),
                ('vehicles_involved', models.IntegerField()),
                ('casualties', models.IntegerField()),
                ('is_peak_hour', models.BooleanField()),
                ('custom_risk_score', models.FloatField()),
            ],
            options={
                'db_table': 'accidents',
            },
        ),
    ]
