# Generated by Django 5.2.16 on 2026-08-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('cluster_id', models.IntegerField()),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('avg_risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('accident_count', models.IntegerField()),
            ],
        ),
    ]
