# Generated by Django 5.2.16 on 2026-08-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotspotcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotcluster',
            name='area_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
