# Generated by Django 5.2.16 on 2026-08-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotspotcluster_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
