# Generated by Django 5.2.16 on 2026-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accident_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='visibility',
            field=models.IntegerField(),
        ),
    ]
