# Generated by Django 5.2.16 on 2026-09-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accident_location_alter_accident_accident_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('issue_type', models.CharField(choices=[('pothole', 'Pothole'), ('signal_failure', 'Traffic Signal Failure'), ('unsafe_crossing', 'Unsafe Pedestrian Crossing'), ('poor_lighting', 'Poor Street Lighting'), ('missing_signage', 'Missing Road Signage'), ('other', 'Other Safety Issue')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('coverage_status', models.CharField(choices=[('InCoverage', 'InCoverage'), ('OutOfCoverage', 'OutOfCoverage')], default='InCoverage', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_reports',
                'ordering': ['-timestamp'],
            },
        ),
    ]
